[package]
name = "win-proc-mem"
version = "0.1.0"
edition = "2021"

[dependencies]
windows={version="0.34.0", features= [
    "Win32_System_Threading",
    "Win32_Foundation",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Diagnostics_Debug",
]}
thiserror="1.0.30"